const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Behaviors.NoSave,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Behaviors.aekiro_gameobject,
		C3.Behaviors.aekiro_scrollView,
		C3.Behaviors.Sin,
		C3.Plugins.Json,
		C3.Behaviors.aekiro_button,
		C3.Plugins.NinePatch,
		C3.Behaviors.Fade,
		C3.Behaviors.Timer,
		C3.Behaviors.aekiro_checkbox,
		C3.Plugins.sliderbar,
		C3.Behaviors.aekiro_progress,
		C3.Plugins.Dictionary,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.scrollto,
		C3.Plugins.Timeline,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.aekiro_proui,
		C3.Plugins.Date,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Exps.Get,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.ScriptsInEvents.Mainevents_Event2_Act1,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.ScriptsInEvents.Mainevents_Event2_Act3,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.InstanceSignal,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Exps.At,
		C3.ScriptsInEvents.Mainevents_Event33_Act1,
		C3.ScriptsInEvents.Mainevents_Event34_Act1,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.ScriptsInEvents.Mainevents_Event63_Act1,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.ScriptsInEvents.Mainevents_Event68_Act1,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.TotalTime,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.ScriptsInEvents.Settingsevents_Event2_Act1,
		C3.ScriptsInEvents.Settingsevents_Event3_Act1,
		C3.ScriptsInEvents.Settingsevents_Event5_Act1,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.sliderbar.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.aekiro_checkbox.Cnds.OnClicked,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.OnResume,
		C3.ScriptsInEvents.Adevents_Event2_Act1,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.ScriptsInEvents.Adevents_Event3_Act1,
		C3.ScriptsInEvents.Adevents_Event5_Act2,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetEffectEnabled,
		C3.Plugins.aekiro_proui.Acts.Init,
		C3.Behaviors.aekiro_scrollView.Acts.setEnabled,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Acts.AddTo,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.aekiro_scrollView.Acts.ScrollBy,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.aekiro_button.Acts.setEnabled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Behaviors.aekiro_progress.Acts.SetMaxValue,
		C3.Behaviors.aekiro_progress.Acts.setValue,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Fade.Cnds.OnWaitEnd,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Cnds.OnInstanceSignal,
		C3.Plugins.Date.Exps.ToTotalSeconds,
		C3.Plugins.Date.Exps.Difference,
		C3.Plugins.Date.Exps.Now,
		C3.ScriptsInEvents.Offlineevent_Event15_Act1,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.ScriptsInEvents.Startevents_Event1_Act2,
		C3.ScriptsInEvents.Startevents_Event1_Act4,
		C3.ScriptsInEvents.Startevents_Event1_Act5,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Физика: 0},
	{НеСохранять: 0},
	{BoxBoundery: 0},
	{BoxLimiter: 0},
	{BuyBox: 0},
	{Спрайт: 0},
	{LabelMoneyLetter: 0},
	{Твинанимация: 0},
	{LabelMoneyZero: 0},
	{LevelObjects: 0},
	{StaticObject: 0},
	{type: 0},
	{Crusher: 0},
	{Прикрепить: 0},
	{Tooth: 0},
	{значение_яркости: 0},
	{health: 0},
	{тип: 0},
	{Ore: 0},
	{Spawner: 0},
	{PoolOresL: 0},
	{PoolOresM: 0},
	{OreParticle: 0},
	{ParticleDestroy: 0},
	{PoolObjects: 0},
	{PoolCristalls: 0},
	{ConveerPhysics: 0},
	{ConveerTiled: 0},
	{ConveerMask: 0},
	{GameObject: 0},
	{ИконкаСкин: 0},
	{СкинДоступин: 0},
	{ФонСкин: 0},
	{ФонСкиныЛок: 0},
	{ТекстИнфоСкин: 0},
	{ТекстСкинПрогресс: 0},
	{BackObjectSkins: 0},
	{ScrollView: 0},
	{ScrollViewSkins: 0},
	{BarSkins: 0},
	{Синусоид: 0},
	{ЗначокСкина: 0},
	{changeFrame: 0},
	{tuch: 0},
	{enable: 0},
	{Over: 0},
	{КнопкаЗакрытьСкины: 0},
	{КнопкаСкин: 0},
	{SliderBarSkins: 0},
	{СкинСпрайт: 0},
	{DataSkinsJson: 0},
	{Button: 0},
	{ТекстЦенаАпгрейд: 0},
	{ТекстИнфоАпгрейд: 0},
	{КнопкаЛевая: 0},
	{КнопкаПравая: 0},
	{ИконкаАпгрейд: 0},
	{ИмяАпгрейд: 0},
	{КнопкаАп: 0},
	{visibilityArrows: 0},
	{textHint: 0},
	{minValue: 0},
	{maxValue: 0},
	{currentValue: 0},
	{stepValue: 0},
	{valuePrefix: 0},
	{maxLevel: 0},
	{currentLevel: 0},
	{needLevel: 0},
	{price: 0},
	{multipPrice: 0},
	{geometricProgres: 0},
	{multipValue: 0},
	{БлокАпгрейд: 0},
	{МассивЦены: 0},
	{BackObjectShop: 0},
	{BarShop: 0},
	{ScrollViewShop: 0},
	{СинусоидОпасити: 0},
	{СинусоидДвижение: 0},
	{ИконкаПомощь: 0},
	{SliderBarShop: 0},
	{Угасание: 0},
	{ТекстПодсказка: 0},
	{ПанельПодсказка: 0},
	{DataShopJson: 0},
	{BombArea: 0},
	{Таймер: 0},
	{BombObject: 0},
	{LabelBomb: 0},
	{ButtonSettings: 0},
	{Checkbox: 0},
	{CheckBoxEffects: 0},
	{ResetButton: 0},
	{SliderMusic: 0},
	{SliderSound: 0},
	{КнопкаАппУровень: 0},
	{КнопкаСобратьУровень: 0},
	{РудаИконкаАП: 0},
	{ШкалаУровень: 0},
	{ШкалаФонУровень: 0},
	{ТекстНаградаУровень: 0},
	{ТекстУровень: 0},
	{КнопкаРеклама: 0},
	{ЗначокБонуса: 0},
	{КнопкиБонус: 0},
	{ТекстТаймерБонуса: 0},
	{ЧастицаРеклама: 0},
	{выполнено: 0},
	{Открыто: 0},
	{КнопкаЗадания: 0},
	{КнопкаЗакрытьЗадания: 0},
	{КнопкаСобрать: 0},
	{номер_задания: 0},
	{ПлашкаЗадания: 0},
	{ТекстЗадание: 0},
	{ТекстНаграда: 0},
	{ТекстПрогресЗадания: 0},
	{ФонШкалаЗадание: 0},
	{Progress: 0},
	{ШкалаЗадания: 0},
	{МассивЗадания: 0},
	{PoolTasks: 0},
	{GlobalVars: 0},
	{DataObject: 0},
	{Мышь: 0},
	{Тач: 0},
	{GameControler: 0},
	{Перетаскивание: 0},
	{СледитьЗа: 0},
	{Camera: 0},
	{ClickEffect: 0},
	{СпрайтКЛИК: 0},
	{ParticleClickEffect: 0},
	{ВременнаяШкала: 0},
	{number: 0},
	{Array: 0},
	{AJAX: 0},
	{Аудио: 0},
	{ФонЗадания: 0},
	{DarkeningBackground: 0},
	{ProUI: 0},
	{угол_движения: 0},
	{ЧастицаСпрайтЗадания: 0},
	{СтатОбъект: 0},
	{ТекстОффлайнДоход: 0},
	{КнопкаОфлайнДоход: 0},
	{Дата: 0},
	{СпрайтФонЛого: 0},
	{ЛогоCrGa: 0},
	{ЛогоLeGA: 0},
	{Браузер: 0},
	{ДанныеЗагрузки: 0},
	{МассивСкины: 0},
	{КнопкаОбучение: 0},
	{ТекстОбучение: 0},
	{СинусоидКлик: 0},
	{СинусоидСвайп: 0},
	{ИконкаТач: 0},
	{этап: 0},
	{ПанельОбучение: 0},
	{TwinEffects: 0},
	{TwinButton: 0},
	{BrightnessEffect: 0},
	{SpeedCrusher: 0},
	{Damage: 0},
	{CountTooth: 0},
	{ScaleTooth: 0},
	{CrusherGearbox: 0},
	{angleOffset: 0},
	{value: 0},
	{SpawnTime: 0},
	{CountSpawn: 0},
	{OpenOres: 0},
	{Gravity: 0},
	{ChanceCristal: 0},
	{PriceOre: 0},
	{currentChance: 0},
	{CountCristallOnLayout: 0},
	{damag: 0},
	{xPosition: 0},
	{yPosition: 0},
	{animFrame: 0},
	{animName: 0},
	{uidOre: 0},
	{startPrice: 0},
	{sum: 0},
	{ConveerSpeed: 0},
	{Money: 0},
	{СуммаДПС: 0},
	{DPS: 0},
	{ИмяСохранения: 0},
	{version: 0},
	{speedAnim: 0},
	{var: 0},
	{час: 0},
	{мин: 0},
	{сек: 0},
	{enable_hour: 0},
	{данные: 0},
	{BombSpawnTime: 0},
	{OpenBomb: 0},
	{Blinking: 0},
	{AnimOres: 0},
	{nameSound: 0},
	{speed: 0},
	{Уровень: 0},
	{ТекущиеОчкиУровень: 0},
	{НеобходимыеОчкиУровень: 0},
	{НаградаЗаУровень: 0},
	{PointsMultiplier: 0},
	{BonusX2: 0},
	{BonusX5: 0},
	{УидКнопки: 0},
	{уид: 0},
	{SkinSelected: 0},
	{кадр_скина: 0},
	{показать: 0},
	{frame: 0},
	{action: 0},
	{кадр: 0},
	{видимость: 0},
	{timeArrow: 0},
	{уид_плашки: 0},
	{кол_во: 0},
	{номер: 0},
	{posX: 0},
	{posY: 0},
	{ПроцентОффлайнДоход: 0},
	{ПроцентДохода: 0},
	{меткаВремени: 0},
	{офлайнДоход: 0},
	{ДПС_ОФФ: 0},
	{сумма: 0},
	{имя_слоя: 0},
	{секунды: 0},
	{переменная: 0},
	{переменная2: 0},
	{тип2: 0},
	{SaveTry: 0},
	{TutorialStage: 0},
	{х: 0},
	{у: 0},
	{stage: 0}
];

self.InstanceType = {
	BoxBoundery: class extends self.ITiledBackgroundInstance {},
	BoxLimiter: class extends self.ISpriteInstance {},
	BuyBox: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	LabelMoneyLetter: class extends self.ITextInstance {},
	LabelMoneyZero: class extends self.ITextInstance {},
	LevelObjects: class extends self.ISpriteInstance {},
	StaticObject: class extends self.ISpriteInstance {},
	Crusher: class extends self.ISpriteInstance {},
	Tooth: class extends self.ISpriteInstance {},
	Ore: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	PoolOresL: class extends self.IArrayInstance {},
	PoolOresM: class extends self.IArrayInstance {},
	OreParticle: class extends self.ISpriteInstance {},
	ParticleDestroy: class extends self.IParticlesInstance {},
	PoolObjects: class extends self.ISpriteInstance {},
	PoolCristalls: class extends self.IArrayInstance {},
	ConveerPhysics: class extends self.ISpriteInstance {},
	ConveerTiled: class extends self.ITiledBackgroundInstance {},
	ConveerMask: class extends self.ITiledBackgroundInstance {},
	ИконкаСкин: class extends self.ISpriteInstance {},
	СкинДоступин: class extends self.ISpriteInstance {},
	ФонСкин: class extends self.ISpriteInstance {},
	ФонСкиныЛок: class extends self.ISpriteInstance {},
	ТекстИнфоСкин: class extends self.ITextInstance {},
	ТекстСкинПрогресс: class extends self.ITextInstance {},
	BackObjectSkins: class extends self.ITiledBackgroundInstance {},
	ScrollViewSkins: class extends self.ISpriteInstance {},
	BarSkins: class extends self.ISpriteInstance {},
	ЗначокСкина: class extends self.ISpriteInstance {},
	КнопкаЗакрытьСкины: class extends self.ISpriteInstance {},
	КнопкаСкин: class extends self.ISpriteInstance {},
	SliderBarSkins: class extends self.ISpriteInstance {},
	СкинСпрайт: class extends self.ISpriteInstance {},
	DataSkinsJson: class extends self.IJSONInstance {},
	ТекстЦенаАпгрейд: class extends self.ITextInstance {},
	ТекстИнфоАпгрейд: class extends self.ITextInstance {},
	КнопкаЛевая: class extends self.ISpriteInstance {},
	КнопкаПравая: class extends self.ISpriteInstance {},
	ИконкаАпгрейд: class extends self.ISpriteInstance {},
	ИмяАпгрейд: class extends self.ISpriteInstance {},
	КнопкаАп: class extends self.ISpriteInstance {},
	БлокАпгрейд: class extends self.ISpriteInstance {},
	МассивЦены: class extends self.IArrayInstance {},
	BackObjectShop: class extends self.ITiledBackgroundInstance {},
	BarShop: class extends self.ISpriteInstance {},
	ScrollViewShop: class extends self.IWorldInstance {},
	ИконкаПомощь: class extends self.ISpriteInstance {},
	SliderBarShop: class extends self.ISpriteInstance {},
	ТекстПодсказка: class extends self.ITextInstance {},
	ПанельПодсказка: class extends self.ISpriteInstance {},
	DataShopJson: class extends self.IJSONInstance {},
	BombArea: class extends self.ISpriteInstance {},
	BombObject: class extends self.ISpriteInstance {},
	LabelBomb: class extends self.ITextInstance {},
	ButtonSettings: class extends self.ISpriteInstance {},
	CheckBoxEffects: class extends self.ISpriteInstance {},
	ResetButton: class extends self.ISpriteInstance {},
	SliderMusic: class extends self.ISliderBarInstance {},
	SliderSound: class extends self.ISliderBarInstance {},
	КнопкаАппУровень: class extends self.ISpriteInstance {},
	КнопкаСобратьУровень: class extends self.ISpriteInstance {},
	РудаИконкаАП: class extends self.ISpriteInstance {},
	ШкалаУровень: class extends self.ITiledBackgroundInstance {},
	ШкалаФонУровень: class extends self.ISpriteInstance {},
	ТекстНаградаУровень: class extends self.ITextInstance {},
	ТекстУровень: class extends self.ITextInstance {},
	КнопкаРеклама: class extends self.ISpriteInstance {},
	ЗначокБонуса: class extends self.ISpriteInstance {},
	КнопкиБонус: class extends self.ISpriteInstance {},
	ТекстТаймерБонуса: class extends self.ITextInstance {},
	ЧастицаРеклама: class extends self.IParticlesInstance {},
	КнопкаЗадания: class extends self.ISpriteInstance {},
	КнопкаЗакрытьЗадания: class extends self.ISpriteInstance {},
	КнопкаСобрать: class extends self.ISpriteInstance {},
	ПлашкаЗадания: class extends self.ISpriteInstance {},
	ТекстЗадание: class extends self.ITextInstance {},
	ТекстНаграда: class extends self.ITextInstance {},
	ТекстПрогресЗадания: class extends self.ITextInstance {},
	ФонШкалаЗадание: class extends self.ISpriteInstance {},
	ШкалаЗадания: class extends self.ITiledBackgroundInstance {},
	МассивЗадания: class extends self.IArrayInstance {},
	PoolTasks: class extends self.IArrayInstance {},
	GlobalVars: class extends self.IDictionaryInstance {},
	DataObject: class extends self.IJSONInstance {},
	Мышь: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	GameControler: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	ClickEffect: class extends self.ISpriteInstance {},
	СпрайтКЛИК: class extends self.ISpriteInstance {},
	ParticleClickEffect: class extends self.IParticlesInstance {},
	ВременнаяШкала: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	ФонЗадания: class extends self.ISpriteInstance {},
	DarkeningBackground: class extends self.ITiledBackgroundInstance {},
	ProUI: class extends self.IInstance {},
	ЧастицаСпрайтЗадания: class extends self.ISpriteInstance {},
	СтатОбъект: class extends self.ISpriteInstance {},
	ТекстОффлайнДоход: class extends self.ITextInstance {},
	КнопкаОфлайнДоход: class extends self.ISpriteInstance {},
	Дата: class extends self.IInstance {},
	СпрайтФонЛого: class extends self.ISpriteInstance {},
	ЛогоCrGa: class extends self.ISpriteInstance {},
	ЛогоLeGA: class extends self.ISpriteInstance {},
	Браузер: class extends self.IInstance {},
	ДанныеЗагрузки: class extends self.IJSONInstance {},
	МассивСкины: class extends self.IArrayInstance {},
	КнопкаОбучение: class extends self.ISpriteInstance {},
	ТекстОбучение: class extends self.ITextInstance {},
	ИконкаТач: class extends self.ISpriteInstance {},
	ПанельОбучение: class extends self.ISpriteInstance {},
	TwinEffects: class extends self.ISpriteInstance {},
	TwinButton: class extends self.ISpriteInstance {},
	BrightnessEffect: class extends self.ISpriteInstance {}
}